### ISSUE TITLE
Revise DFDs

### ISSUE THREAD

**Issue by emilyvstokes** [S18MIS4173Team10/Team10#1]

**Comment by ClintonKeener** [comment]
Use Cases have been updated to include:  Proper format and flow through Summary Inputs, Source, Outputs, and Destination.  UC Fragments have been updated to mirror changes.

**Comment by ClintonKeener** [comment]
This document contains updated  SUMMARY INPUTS, SOURCE, OUTPUTS, and DESTINATION.  Nothing else was changed on this document.
[Milestone 2 Analysis-MAS-Contains Revised Use Cases 2.docx](https://github.com/S18MIS4173Team10/Team10/files/1899298/Milestone.2.Analysis-MAS-Contains.Revised.Use.Cases.2.docx)

**Comment by ClintonKeener** [comment]
Here are all of the screen shots of the fragments and Level 1's.  The Level 0 is in PDF format because it's larger than 8.5x11.
![uc4 level 1](https://user-images.githubusercontent.com/35353032/38625768-37112704-3d79-11e8-885f-ec315596f34b.JPG)
![uc5 fragment](https://user-images.githubusercontent.com/35353032/38625769-371d8d28-3d79-11e8-8bd9-f260ef917c44.JPG)
![uc5 level 1](https://user-images.githubusercontent.com/35353032/38625770-372a9cac-3d79-11e8-9656-10d66b423307.JPG)
![uc6 fragment](https://user-images.githubusercontent.com/35353032/38625771-3738c85e-3d79-11e8-8ba4-af8112b17663.JPG)
[MS3 DFD Copy 2.pdf](https://github.com/S18MIS4173Team10/Team10/files/1899396/MS3.DFD.Copy.2.pdf)
![uc1 fragment](https://user-images.githubusercontent.com/35353032/38625772-3754998a-3d79-11e8-935d-2bdbae31cec4.JPG)
![uc2 fragment](https://user-images.githubusercontent.com/35353032/38625773-375fbafe-3d79-11e8-870c-d6042d4c57d3.JPG)
![uc3 fragment](https://user-images.githubusercontent.com/35353032/38625774-3769587a-3d79-11e8-8d4d-9305608df75f.JPG)
![uc3 level 1](https://user-images.githubusercontent.com/35353032/38625775-37741e0e-3d79-11e8-808a-6a597aeb1dda.JPG)
![uc4 fragment](https://user-images.githubusercontent.com/35353032/38625776-3784cbf0-3d79-11e8-9238-e62b954d7086.JPG)

**Comment by emilyvstokes** [comment]
awesome, Clinton!
